name: Cucumber Tests with Playwright

# Kích hoạt workflow khi push hoặc pull request vào nhánh main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest # Hệ điều hành chạy pipeline

    steps:
      # Bước 1: Lấy mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Chọn phiên bản Node.js phù hợp

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Cài đặt Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Bước 5: Chạy kiểm thử Cucumber
      - name: Run Cucumber tests
        run: npm run test

      # Bước 6: Tạo báo cáo HTML (nếu dùng cucumber-html-reporter)
      - name: Generate HTML report
        if: always() # Chạy bước này ngay cả khi kiểm thử thất bại
        run: npm run report

      # Bước 7: Lưu báo cáo dưới dạng artifact
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: reports/
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test # Chỉ chạy deploy nếu test pass
  #   if: github.event_name == 'push' # Chỉ deploy khi push vào main, không phải pull request

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Deploy to Vercel (ví dụ)
  #       uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }} # Thêm token Vercel vào Secrets của GitHub
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         working-directory: ./ # Thư mục chứa ứng dụng (nếu cần)